# Generated by Django 3.0.8 on 2020-07-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artists',
            new_name='Artist',
        ),
    ]
